server:
  port: 8081

spring:
  application:
    name: 'booklibrary'

client:
  bookapp-api:
    base-url: http://localhost:8080
    connection-timeout: 10000
    read-timeout: 10000
    call-timeout: 10000